### ISSUE TITLE
Add alias to spec 

### ISSUE THREAD

**Issue by zekroTJA** [zekroTJA/ranna#6]
Add aliases to spec in form of `spec pointers`. This would look like following in the spec configuration:
```yaml
openjdk-11:
  image:      'openjdk:11'
  entrypoint: 'java'
  filename:   'Main.java'

java:
  use:        'openjdk-11'
```
